[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
    -DF_CPU=16000000UL
    -DBAUD_RATE=115200
    -Os
    -Wall
    -ffunction-sections
    -fdata-sections
build_src_filter = +<*>
build_type = release
upload_speed = 115200
monitor_speed = 115200

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags =
    -DF_CPU=16000000UL
    -DBAUD_RATE=115200
    -Os
    -Wall
    -ffunction-sections
    -fdata-sections
build_src_filter = +<*>
build_type = release
upload_speed = 57600
monitor_speed = 115200